# Generated by Django 4.1.7 on 2023-03-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategroiya nomi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Mashinalar',
                'verbose_name_plural': 'Mashinalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Tovar surati')),
                ('price', models.PositiveBigIntegerField(verbose_name='Tovar narxi')),
                ('quan', models.PositiveIntegerField(verbose_name='Soni')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanzac_app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Chexollar',
                'verbose_name_plural': 'Chexollar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Ism')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram id')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Raqam')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Video')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanzac_app.product')),
            ],
            options={
                'verbose_name': 'Tovar vidolari',
                'verbose_name_plural': 'Tovar vidolari',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanzac_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanzac_app.user')),
            ],
            options={
                'verbose_name': 'Buyurmalar',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
