# Generated by Django 4.1.7 on 2023-03-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanzac_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Tovar videolari', 'verbose_name_plural': 'Tovar videolari'},
        ),
    ]
