# Generated by Django 4.1.7 on 2023-03-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanzac_app', '0002_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanzac_app.product', verbose_name='Chexol'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanzac_app.user', verbose_name='Foydalanuvchi'),
        ),
    ]
