# Generated by Django 4.1.7 on 2023-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanzac_app', '0003_alter_order_product_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descr',
            field=models.TextField(default=1, verbose_name='Tavsifi'),
            preserve_default=False,
        ),
    ]
